#!/usr/bin/env bash

set -euo pipefail

SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  SOURCE_DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  case "$SOURCE" in
    /*) ;;
    *) SOURCE="$SOURCE_DIR/$SOURCE" ;;
  esac
done
SCRIPT_DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INVENTORY="${LATER_DEVICE_INVENTORY:-$REPO_ROOT/ops/device-inventory.json}"
OUTPUT=""

usage() {
  cat <<'EOF' >&2
Usage: ./scripts/render-device-ssh-config.sh [--inventory FILE] [--output FILE]

Renders deterministic OpenSSH Host blocks from the device inventory. Without
--output, writes to stdout. This command never reads or emits private keys.
EOF
  exit 2
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --inventory)
      [ "$#" -ge 2 ] || usage
      INVENTORY="$2"
      shift 2
      ;;
    --output)
      [ "$#" -ge 2 ] || usage
      OUTPUT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      usage
      ;;
  esac
done

[ -r "$INVENTORY" ] || { echo "ERROR: inventory is not readable: $INVENTORY" >&2; exit 1; }
LATER_DEVICE_INVENTORY="$INVENTORY" "$REPO_ROOT/scripts/device-access.sh" check >/dev/null

render() {
  local bastion_alias bastion_host bastion_port bastion_user loopback identity timeout prefix
  local id alias account mode host port

  bastion_alias="$(jq -r '.bastion.sshAlias' "$INVENTORY")"
  bastion_host="$(jq -r '.bastion.host' "$INVENTORY")"
  bastion_port="$(jq -r '.bastion.port' "$INVENTORY")"
  bastion_user="$(jq -r '.bastion.forwardUser' "$INVENTORY")"
  loopback="$(jq -r '.bastion.loopbackAddress' "$INVENTORY")"
  identity="$(jq -r '.defaults.identityFile' "$INVENTORY")"
  timeout="$(jq -r '.defaults.connectTimeoutSeconds' "$INVENTORY")"
  prefix="$(jq -r '.defaults.hostKeyAliasPrefix' "$INVENTORY")"

  cat <<EOF
# Generated from ops/device-inventory.json by scripts/render-device-ssh-config.sh.
# Do not edit this file directly; update the inventory and regenerate it.
# Final targets authenticate the source device end-to-end with its mesh key.

Host $bastion_alias
  HostName $bastion_host
  Port $bastion_port
  User $bastion_user
  IdentityFile $identity
  IdentitiesOnly yes
  BatchMode yes
  ForwardAgent no
  StrictHostKeyChecking yes
  ConnectTimeout $timeout
  ServerAliveInterval 20
  ServerAliveCountMax 3
EOF

  while IFS=$'\t' read -r id alias account mode host port; do
    printf '\nHost %s\n' "$alias"
    printf '  HostName %s\n' "$host"
    printf '  Port %s\n' "$port"
    printf '  User %s\n' "$account"
    if [ "$mode" = "relay" ]; then
      printf '  ProxyJump %s\n' "$bastion_alias"
      printf '  HostKeyAlias %s%s\n' "$prefix" "$id"
    fi
    printf '  IdentityFile %s\n' "$identity"
    printf '  IdentitiesOnly yes\n'
    printf '  BatchMode yes\n'
    printf '  ForwardAgent no\n'
    printf '  StrictHostKeyChecking yes\n'
    printf '  ConnectTimeout %s\n' "$timeout"
  done < <(jq -r --arg loopback "$loopback" '
    .devices[] |
    [
      .id,
      .sshAlias,
      .account,
      .management.mode,
      (if .management.mode == "relay" then $loopback else .management.host end),
      (if .management.mode == "relay" then .management.relayPort else .management.port end)
    ] | @tsv
  ' "$INVENTORY")
}

if [ -n "$OUTPUT" ]; then
  output_dir="$(cd "$(dirname "$OUTPUT")" && pwd)"
  tmp="$(mktemp "$output_dir/.later-devices.XXXXXX")"
  trap 'rm -f "$tmp"' EXIT HUP INT TERM
  render > "$tmp"
  chmod 0644 "$tmp"
  mv "$tmp" "$OUTPUT"
  trap - EXIT HUP INT TERM
else
  render
fi
